#! /usr/bin/env python3

from getpass import getpass
from passlib.hash import sha512_crypt

plaintext_password = getpass()
encrypted_password = sha512_crypt.using(rounds=5000).hash(plaintext_password)
print(encrypted_password)
